// The client's pure core in FSI: the shared contract's DLL, then the core's own files in the
// order the project compiles them. Build first (dotnet run build) so that the DLL is there.
#r "../../Informedica.GenPRES.Shared/bin/Debug/net10.0/Informedica.GenPRES.Shared.dll"

#load "../Deferred.fs"
#load "../FilterSync.fs"
#load "../TermText.fs"
#load "../LanguagePolicy.fs"
#load "../OrderContextRefusalPolicy.fs"
#load "../PatientDraftPolicy.fs"
#load "../PatientReadiness.fs"
#load "../PickPolicy.fs"
#load "../SeverityReasonPolicy.fs"
#load "../ArgumentationPolicy.fs"
#load "../QuantityModePolicy.fs"
#load "../FieldOpenPolicy.fs"
#load "../PickList.fs"
#load "../PlanContextPolicy.fs"
#load "../PlanCellPolicy.fs"
#load "../SectionFoldPolicy.fs"
#load "../TotalsChangePolicy.fs"
#load "../PlanWorkPolicy.fs"
#load "../HeldContextPolicy.fs"
#load "../SessionMachine.fs"
#load "../SigningMachine.fs"
#load "../SessionGatePolicy.fs"
#load "../SigningPolicy.fs"
#load "../UnsignedWorkPolicy.fs"
#load "../OrderPlanMachine.fs"
#load "../OrderContextMachine.fs"
#load "../Trail.fs"
