namespace PaketLoadScripts

#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.AspNetCore.Http.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.Configuration.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.Configuration.EnvironmentVariables.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.Configuration.FileExtensions.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.DependencyInjection.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.FileProviders.Physical.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.Hosting.Abstractions.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.Logging.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\Microsoft.Extensions.Options.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Diagnostics.DiagnosticSource.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Reflection.Metadata.fsx" 