namespace PaketLoadScripts

#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Collections.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Diagnostics.Debug.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Diagnostics.Tools.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Globalization.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.IO.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Reflection.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Resources.ResourceManager.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Runtime.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Runtime.Extensions.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Text.Encoding.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Threading.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\Server\\System.Xml.ReaderWriter.fsx" 
#r "System.Xml.Linq" 