#load "../../../scripts/load-dependencies.fsx"


#r "../../../src/Informedica.Utils.Lib/bin/Debug/net10.0/Informedica.Utils.Lib.dll"
#r "../../../src/Informedica.Agents.Lib/bin/Debug/net10.0/Informedica.Agents.Lib.dll"
#r "../../../src/Informedica.Logging.Lib/bin/Debug/net10.0/Informedica.Logging.Lib.dll"
#r "../../../src/Informedica.GenUnits.Lib/bin/Debug/net10.0/Informedica.GenUnits.Lib.dll"
#r "../../../src/Informedica.GenCore.Lib/bin/Debug/net10.0/Informedica.GenCore.Lib.dll"
#r "../../../src/Informedica.ZIndex.Lib/bin/Debug/net10.0/Informedica.ZIndex.Lib.dll"
#r "../../../src/Informedica.ZForm.Lib/bin/Debug/net10.0/Informedica.ZForm.Lib.dll"
#r "../../../src/Informedica.GenSolver.Lib/bin/Debug/net10.0/Informedica.GenSolver.Lib.dll"
#r "../../../src/Informedica.GenForm.Lib/bin/Debug/net10.0/Informedica.GenForm.Lib.dll"
#r "../../../src/Informedica.GenOrder.Lib/bin/Debug/net10.0/Informedica.GenOrder.Lib.dll"
#r "../../../src/Informedica.GenPRES.Shared/bin/Debug/net10.0/Informedica.GenPRES.Shared.dll"

#load "../../../src/Informedica.GenPRES.Server/Logging.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.Mappers.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.Ports.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.Services.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.Adapters.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.Command.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.CompositionRoot.fs"
#load "../../../src/Informedica.GenPRES.Server/ServerApi.ApiImpl.fs"
