namespace PaketLoadScripts

#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Giraffe.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Antiforgery.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Authentication.Cookies.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Authentication.JwtBearer.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Authentication.OAuth.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Authorization.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Cors.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.ResponseCompression.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Rewrite.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.Session.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.AspNetCore.StaticFiles.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net472\\Server\\Microsoft.Extensions.Caching.Memory.fsx" 
#r "C:\\Users\\halcw\\.nuget\\packages\\saturn\\0.8.0\\lib\\netstandard2.0\\Saturn.dll" 