namespace PaketLoadScripts

#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Collections.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.IO.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Resources.ResourceManager.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Runtime.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Runtime.Extensions.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Runtime.Handles.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Runtime.InteropServices.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Runtime.Numerics.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Security.Cryptography.Encoding.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Security.Cryptography.Primitives.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Text.Encoding.fsx" 
#r "System.Core" 
#r "C:\\Users\\halcw\\.nuget\\packages\\system.security.cryptography.algorithms\\4.3.1\\lib\\net461\\System.Security.Cryptography.Algorithms.dll" 