namespace PaketLoadScripts

#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Collections.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Diagnostics.Debug.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Diagnostics.Tracing.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Globalization.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.IO.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Net.Http.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Net.Primitives.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Net.WebHeaderCollection.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Resources.ResourceManager.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Runtime.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Threading.fsx" 
#load "C:\\Development\\Informedica\\apps\\GenPres2\\.paket\\load\\net462\\ServerTests\\System.Threading.Tasks.fsx" 
#r "System" 