#r "nuget: Unquote"
#r "nuget: MathNet.Numerics.FSharp"
#r "nuget: Newtonsoft.Json"
#r "nuget: ConsoleTables"

#load "../Continuation.fs"
#load "../Constants.fs"
#load "../Memoization.fs"
#load "../Reflection.fs"
#load "../NullCheck.fs"
#load "../BCL/Boolean.fs"
#load "../BCL/Char.fs"
#load "../BCL/String.fs"
#load "../BCL/Int32.fs"
#load "../BCL/Double.fs"
#load "../BCL/BigInteger.fs"
#load "../BCL/BigRational.fs"
#load "../BCL/DateTime.fs"
#load "../BCL/Decimal.fs"
#load "../BCL/Tuple.fs"
#load "../Json.fs"
#load "../Option.fs"
#load "../StringBuilder.fs"
#load "../Result.fs"
#load "../Array.fs"
#load "../List.fs"
#load "../Seq.fs"
#load "../Set.fs"
#load "../RingBuffer.fs"
#load "../Path.fs"
#load "../File.fs"
#load "../Csv.fs"
#load "../Web.fs"
#load "../Env.fs"
#load "../App.fs"
#load "../Console.fs"
#load "../ConsoleTables.fs"
#load "../StopWatch.fs"

